from _typeshed import Incomplete

class TuringDBException(Exception):
    def __init__(self, message: str) -> None: ...

class TuringDB:
    DEFAULT_HEADERS: Incomplete
    host: Incomplete
    def __init__(self, instance_id: str = '', auth_token: str = '', host: str = 'https://engines.turingdb.ai/sdk') -> None: ...
    def list_available_graphs(self) -> list[str]: ...
    def list_loaded_graphs(self) -> list[str]: ...
    def load_graph(self, graph_name: str, raise_if_loaded: bool = True): ...
    def create_graph(self, graph_name: str): ...
    def query(self, query: str): ...
    def set_commit(self, commit: str): ...
    def set_change(self, change: str): ...
    def checkout(self, change: str = 'main', commit: str = 'HEAD'): ...
    def set_graph(self, graph_name: str): ...
