from .exceptions import TuringDBException as TuringDBException
from .path import PathType as PathType
from .protocol import QueryProtocol as QueryProtocol

class S3Client:
    def __init__(self, bucket_name: str, access_key: str | None = None, secret_key: str | None = None, region: str | None = None, use_scratch: bool = True) -> None: ...
    def connect(self, query_protocol: QueryProtocol): ...
    def transfer(self, src: str, dst: str): ...
