import click
from . import greeter as greeter
from _typeshed import Incomplete
from turingdb import TuringDB as TuringDB, TuringDBException as TuringDBException

CONTEXT_SETTINGS: Incomplete

class ShellException(Exception): ...

def create_completer(): ...
@click.pass_context
def main(ctx, host, local, auth_token, instance_id) -> None: ...
def start_shell(client: TuringDB): ...
def show_help() -> None: ...
def change_graph(client: TuringDB, args: list[str]): ...
def list_available_graphs(client: TuringDB, args: list[str]): ...
def list_loaded_graphs(client: TuringDB, args: list[str]): ...
