import click
from . import greeter as greeter
from _typeshed import Incomplete
from turingdb import TuringDB as TuringDB, TuringDBException as TuringDBException
from turingdb.turingsh.command import shell_command as shell_command

CONTEXT_SETTINGS: Incomplete

class ShellException(Exception): ...

def create_completer(): ...
@click.pass_context
def main(ctx, host, local, auth_token, instance_id) -> None: ...
def start_shell(client: TuringDB): ...
def show_help() -> None: ...
@shell_command
@click.pass_obj
def checkout(client, commit: str, change: int): ...
@shell_command
@click.pass_obj
def change_graph(client: TuringDB, graph_name: str): ...
@shell_command
@click.pass_obj
def list_available_graphs(client: TuringDB): ...
@shell_command
@click.pass_obj
def list_loaded_graphs(client: TuringDB): ...
