name: CI macos

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest-xlarge

    steps:
    - name: Install UV
      run: wget -qO- https://astral.sh/uv/install.sh | sh

    - name: Install LLVM and recent clang
      run: |
        brew install llvm@20
        echo "CC=$(brew --prefix llvm@20)/bin/clang" >> $GITHUB_ENV
        echo "CXX=$(brew --prefix llvm@20)/bin/clang++" >> $GITHUB_ENV
        echo "LLVM_PATH=$(brew --prefix llvm@20)" >> $GITHUB_ENV
        echo "$(brew --prefix llvm@20)/bin" >> $GITHUB_PATH

    - uses: actions/checkout@v4
      with:
            # Fetch submodules using the built-in token over HTTPS
            submodules: recursive
            # Ensure credentials are set for submodule fetches
            persist-credentials: true

    - name: Install C++ SDK dependencies
      run: core/native/dependencies.sh

    - name: Build
      run: make
